### PR TITLE
added swagger to web-ui-oa2

### PR DESCRIPTION
**Pull request by ramaraosrikakulapu**
Added swagger ui to web-ui-oa2 repo

### CODE REVIEW

**Comment by ramaraosrikakulapu** [comment]
@ayasuda-ge .. Updated the API for user details. Please review the [swagger-ui.json](https://github.com/ramaraosrikakulapu/web-ui-oa2/blob/v1.1beta/assets/swagger-ui/swagger-ui.json) and merge the PR, if every thing looks good.

**Comment by ayasuda-ge** [comment]
please change the "/assets" to "/webui-assets"

**Comment by ayasuda-ge** [comment]
> please change the "/assets" to "/webui-assets"

@ramaraosrikakulapu

**Comment by ramaraosrikakulapu** [comment]
> > please change the "/assets" to "/webui-assets"
> 
> @ramaraosrikakulapu

@ayasuda-ge .. Updated the dir name as suggested.

**Pull request merged**
